FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# dotstamp_server

Polls is a simple API allowing consumers to view polls and vote in them.

## Contribution List [/contribution/list]

### 取得する [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user": {
                    "id": 1,
                    "name": "foo",
                    "profileImageID": 1
                },
                "title": "foo",
                "tag": [
                    {
                        "id": 1,
                        "userContributionID": 1,
                        "name": 1,
                    }
                ],
                "followCount": 1,
                "body": [
                    {
                        "priority": 1,
                        "body": "foo",
                        "directionType": 1,
                        "character": {
                            "id": 1,
                            "fileName": "foo",
                            "voiceType": 1,
                        }
                    }
                ],
                "viewStatus": 1,
                "search": "foo",
                "soundStatus": 1,
                "movie": {
                    "user_contribution_id": 1,
                    "movie_type": 1,
                    "movie_id": "foo",
                    "movie_status": 1,
                    "CreatedAt": "2017-04-24T22:45:00+09:00",
                    "DeletedAt": NULL,
                    "UpdatedAt": "2017-04-24T22:45:00+09:00"
                },
                "createdAt": "2017-04-24T22:45:00+09:00",
                "updatedAt": "2017-04-24T22:45:00+09:00"
            }
        ]

## Contribution New [/contribution/new]

### 投稿を作成する [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "title": "foo",
            "body": "{[投稿データ]}",
            "viewStatus": 1,
            "tag": "foo,bar,foobar"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }