FORMAT: 1A
HOST: http://dotstamp.com/api/

# dotstamp_server

Polls is a simple API allowing consumers to view polls and vote in them.

## users/new [/users/new]

### ユーザを登録する [POST]

+ Request (application/json)

        {
            "email": "wheatandcat@gmail.com",
            "password": "jdhflinjkhfljhk;lnz;klnfhklfn"
        }

+ Response 200 (application/json)

    + Body

            {
                "warning": false,
                "message": "",
                "userID": 1
            }
