FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# dotstamp_server

Polls is a simple API allowing consumers to view polls and vote in them.

## contribution/{id} [/contribution/{id}]
    
+ Parameters
    + id - 投稿ID

### 取得する [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "user": {
                    "id": 1,
                    "name": "foo",
                    "profileImageID": 1
                },
                "title": "foo",
                "tag": [
                    {
                        "id": 1,
                        "userContributionID": 1,
                        "name": 1
                    }
                ],
                "followCount": 1,
                "body": [
                    {
                        "priority": 1,
                        "body": "foo",
                        "directionType": 1,
                        "character": {
                            "id": 1,
                            "fileName": "foo",
                            "voiceType": 1
                        }
                    }
                ],
                "viewStatus": 1,
                "search": "foo",
                "soundStatus": 1,
                "movie": {
                    "user_contribution_id": 1,
                    "movie_type": 1,
                    "movie_id": "foo",
                    "movie_status": 1,
                    "CreatedAt": "2017-04-24T22:45:00+09:00",
                    "DeletedAt": NULL,
                    "UpdatedAt": "2017-04-24T22:45:00+09:00"
                },
                "createdAt": "2017-04-24T22:45:00+09:00",
                "updatedAt": "2017-04-24T22:45:00+09:00",
                "following": true,
                "soundFile": true
            }

### 投稿を更新する [PUT]

+ Request (application/x-www-form-urlencoded)

        {
            "title": "foo",
            "body": "{[投稿データ]}",
            "viewStatus": 1,
        }

+ Response 200 (application/x-www-form-urlencoded)

    + Body

            {
                "{id}"
            }
            
### 投稿を削除する [DELETE]

+ Response 200 (application/x-www-form-urlencoded)

    + Body

            {
                true
            }

## contribution/new [/contribution/new]

### 投稿を作成する [POST]

+ Request (application/x-www-form-urlencoded)

        {
            "title": "foo",
            "body": "{[投稿データ]}",
            "viewStatus": 1,
            "tag": "foo,bar,foobar"
        }

+ Response 200 (application/x-www-form-urlencoded)

    + Body

            {
                "{id}"
            }
            
## contribution/list [/contribution/list]

### リストを取得する [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user": {
                    "id": 1,
                    "name": "foo",
                    "profileImageID": 1
                },
                "title": "foo",
                "tag": [
                    {
                        "id": 1,
                        "userContributionID": 1,
                        "name": 1
                    }
                ],
                "followCount": 1,
                "body": [
                    {
                        "priority": 1,
                        "body": "foo",
                        "directionType": 1,
                        "character": {
                            "id": 1,
                            "fileName": "foo",
                            "voiceType": 1
                        }
                    }
                ],
                "viewStatus": 1,
                "search": "foo",
                "soundStatus": 1,
                "movie": {
                    "user_contribution_id": 1,
                    "movie_type": 1,
                    "movie_id": "foo",
                    "movie_status": 1,
                    "CreatedAt": "2017-04-24T22:45:00+09:00",
                    "DeletedAt": NULL,
                    "UpdatedAt": "2017-04-24T22:45:00+09:00"
                },
                "createdAt": "2017-04-24T22:45:00+09:00",
                "updatedAt": "2017-04-24T22:45:00+09:00"
            }
        ]

## contribution/edit/{id} [/contribution/edit/{id}]

+ Parameters
    + id - 投稿ID

### 編集情報を取得する [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "user": {
                    "id": 1,
                    "name": "foo",
                    "profileImageID": 1
                },
                "title": "foo",
                "tag": [
                    {
                        "id": 1,
                        "userContributionID": 1,
                        "name": 1
                    }
                ],
                "followCount": 1,
                "body": [
                    {
                        "priority": 1,
                        "body": "foo",
                        "directionType": 1,
                        "character": {
                            "id": 1,
                            "fileName": "foo",
                            "voiceType": 1
                        }
                    }
                ],
                "viewStatus": 1,
                "search": "foo",
                "soundStatus": 1,
                "movie": {
                    "user_contribution_id": 1,
                    "movie_type": 1,
                    "movie_id": "foo",
                    "movie_status": 1,
                    "CreatedAt": "2017-04-24T22:45:00+09:00",
                    "DeletedAt": NULL,
                    "UpdatedAt": "2017-04-24T22:45:00+09:00"
                },
                "createdAt": "2017-04-24T22:45:00+09:00",
                "updatedAt": "2017-04-24T22:45:00+09:00",
                "sound": true,
                "soundFile": true
            }

## contribution/search [/contribution/search]

### 検索する [POST]

+ Request (application/x-www-form-urlencoded)

        {
            "search": "foo",
            "order": 1,
            "page": 1,
            "limit": 1
        }

+ Response 200 (application/x-www-form-urlencoded)

    + Body

            {
                list: [
                    {"投稿情報"}
                ],
                count: 1,
            }
            
## contribution/upload{?id} [/contribution/upload{?id}]

+ Parameters
    + id - 投稿ID

### 画像をアップロードする [POST]

+ Request  (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image[file]"; filename="image.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 200 (application/x-www-form-urlencoded)

    + Body

            {
                warning: false,
                message: "",
                path: "14.jpg",
            }